spring:
  application:
    name: lesson5
  cache:
    type: caffeine
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  liquibase:
    change-log: classpath:migrations/db.changelog-master.yaml

server:
  port: 8011
cb:
  currency-url: https://www.cbr.ru/scripts/XML_daily.asp
  currency-cache-name: currenciesCache
kudago:
  category-url: https://kudago.com/public-api/v1.4/place-categories
  location-url: https://kudago.com/public-api/v1.4/locations
  events-url: https://kudago.com/public-api/v1.4/events

resilience4j:
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        failure-rate-threshold: 50
        sliding-window-size: 10
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

app:
  threadpool:
    size: 2
  event-service:
    threadpool:
      size: 2
  scheduled:
    threadpool:
      size: 2
  init:
    schedule: "PT10M"
  rate-limit:
    max-concurrent-requests: 5